export const API_ENDPOINTS = {
  // Auth
  LOGIN: '/auth/login',
  REFRESH_TOKEN: '/auth/refresh',
  LOGOUT: '/auth/logout',

  // Parent Portal
  PARENT_PROFILE: '/portal/my-profile',
  PARENT_CHANGE_PASSWORD: '/portal/change-password',
  PARENT_CHILDREN: '/portal/my-children',
  PARENT_FEES: '/portal/fees',
  PARENT_PAYMENTS: '/portal/payments',
  PARENT_RECEIPTS: '/portal/receipts',
  PARENT_ANNOUNCEMENTS: '/portal/announcements',
  PARENT_NOTICES: '/portal/notices',
  PARENT_NOTIFICATIONS: '/portal/notifications',
  PARENT_CHAT_TEACHERS: '/portal/chat/teachers',
  PARENT_CHAT_MESSAGES: (teacherId) => `/portal/chat/messages/${teacherId}`,
  PARENT_CHAT_SEND: '/portal/chat',
  CHILD_SUMMARY: (studentId) => `/portal/child/${studentId}/summary`,
  CHILD_ATTENDANCE: (studentId) => `/portal/child/${studentId}/attendance`,
  CHILD_HOMEWORK: (studentId) => `/portal/child/${studentId}/homework`,
  CHILD_RESULTS: (studentId) => `/portal/child/${studentId}/results`,
  CHILD_REPORT_CARD: (studentId) => `/portal/child/${studentId}/report-card`,
  CHILD_LIBRARY: (studentId) => `/portal/child/${studentId}/library`,
  CHILD_DOCUMENTS: (studentId) => `/portal/child/${studentId}/documents`,
  CHILD_TRANSPORT: (studentId) => `/portal/child/${studentId}/transport`,
  CHILD_TIMETABLE: (studentId) => `/portal/child/${studentId}/timetable`,
  CHILD_PERFORMANCE: (studentId) => `/portal/child/${studentId}/performance`,

  // Teacher Portal
  TEACHER_PROFILE: '/teacher/profile',
  TEACHER_CHANGE_PASSWORD: '/teacher/change-password',
  TEACHER_CLASSES: '/teacher/my-classes',
  TEACHER_STUDENTS: '/teacher/my-students',
  TEACHER_PAYSLIPS: '/teacher/payslips',
  TEACHER_PAYROLL_HISTORY: '/teacher/payroll-history',
  TEACHER_ANNOUNCEMENTS: '/teacher/announcements',
  TEACHER_NOTICES: '/teacher/notices',
  TEACHER_LEAVE_HISTORY: '/teacher/leave-history',
  TEACHER_LEAVE_APPLY: '/teacher/leave',
  TEACHER_LEAVE_UPDATE: (id) => `/teacher/leave/${id}`,
  TEACHER_LEAVE_DELETE: (id) => `/teacher/leave/${id}`,
  TEACHER_DOCUMENTS: '/teacher/documents',
  TEACHER_MESSAGES: '/teacher/messages',
  TEACHER_CHAT_SEND: '/teacher/chat',
  TEACHER_HOMEWORK: '/teacher/homework',
  TEACHER_HOMEWORK_CREATE: '/teacher/homework',
  TEACHER_HOMEWORK_UPDATE: (id) => `/teacher/homework/${id}`,
  TEACHER_HOMEWORK_DELETE: (id) => `/teacher/homework/${id}`,
  TEACHER_HOMEWORK_SUBMISSIONS: (id) => `/teacher/homework/${id}/submissions`,
  TEACHER_EVALUATE_SUBMISSION: (id, studentId) => `/teacher/homework/${id}/submissions/${studentId}`,
  TEACHER_EXAMS: '/teacher/exams',
  TEACHER_MARKS: '/teacher/marks',
  TEACHER_REPORTS: '/teacher/reports',

  // Principal (School Admin) - using Admin/Dashboard Endpoints
  ADMIN_OVERVIEW: '/dashboard/overview',
  ADMIN_KPIS: '/dashboard/kpis',
  ADMIN_STUDENT_STATS: '/dashboard/students',
  ADMIN_ATTENDANCE_STATS: '/dashboard/attendance',
  ADMIN_FINANCE_STATS: '/dashboard/finance',
  ADMIN_PAYROLL_STATS: '/dashboard/payroll',
  ADMIN_TRANSPORT_STATS: '/dashboard/transport',
  ADMIN_LIBRARY_STATS: '/dashboard/library',
  ADMIN_COMMUNICATION_STATS: '/dashboard/communication',
  ADMIN_INVENTORY_STATS: '/dashboard/inventory',
  ADMIN_ACTIVITY: '/dashboard/activity',
  ADMIN_UPCOMING_EVENTS: '/dashboard/upcoming-events',
  ADMIN_SYSTEM_HEALTH: '/dashboard/system-health',
  ADMIN_LEAVES: '/attendance/leaves',
  ADMIN_LEAVE_STATUS: (id) => `/attendance/leaves/${id}/status`,
  ADMIN_ANNOUNCEMENTS: '/communication/announcements',
  ADMIN_ANNOUNCEMENT_CREATE: '/communication/announcements',
  ADMIN_ANNOUNCEMENT_DELETE: (id) => `/communication/announcements/${id}`
};

export default API_ENDPOINTS;
